server:
  port: 8081
spring:
  application:
    name: USERSERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/usersecurity
    username: lawispringboot
    password: Lawrence
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
